name: CI - Run UI Tests

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotenv@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: '146'

    - name: Restore dependencies
      run: dotnet restore

    - name: Ensure TestResults directory exists
      run: mkdir -p TestResults

    - name: Run tests
      run: dotnet test --logger:"console;verbosity=detailed" --results-directory TestResults --logger "trx;LogFileName=test_results.trx"

    - name: Upload TestResults
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: TestResults
